OnlineStoreFP/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineStoreFP.Models
{
    public partial class ShoppingCart
    {
        public decimal? Userid { get; set; }
        public decimal? Productid { get; set; }
        public decimal Id { get; set; }
        public decimal? Quantity { get; set; }

        public virtual ProductFp Product { get; set; }
        public virtual UserFp User { get; set; }
    }
}

OnlineStoreFP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MimeKit;
using OnlineStoreFP.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace OnlineStoreFP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ModelContext _context;

        public HomeController(ILogger<HomeController> logger , ModelContext context)
        {
            _logger = logger;
            _context = context;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}\
        public IActionResult Index()
        {
            var modelContext1 = _context.ProductFps.Include(p => p.Store.Category).ToList();
            var modelContext2 = _context.CategoryFps.ToList();
            var getall = Tuple.Create<IEnumerable<OnlineStoreFP.Models.ProductFp>, IEnumerable<OnlineStoreFP.Models.CategoryFp>>(modelContext1, modelContext2);
            var custId = HttpContext.Session.GetInt32("CustomerId");
            //ShoppingCart shoppingCart = new ShoppingCart();
            //shoppingCart.Userid = custId;
            //shoppingCart.Productid = 61;

            //_context.Add(shoppingCart);
            return View(getall);
        }
        [HttpPost]
        public async Task<IActionResult> Index( ShoppingCart shoppingCart , int proid)
        {
            var modelContext1 = _context.ProductFps.Include(p => p.Store.Category).ToList();
            var modelContext2 = _context.CategoryFps.ToList();
            var getall = Tuple.Create<IEnumerable<OnlineStoreFP.Models.ProductFp>, IEnumerable<OnlineStoreFP.Models.CategoryFp>>(modelContext1, modelContext2);


            
            //var getall = Tuple.Create<IEnumerable<OnlineStoreFP.Models.ProductFp>, IEnumerable<OnlineStoreFP.Models.CategoryFp>>(modelContext1, modelContext2);
            
            var custId = HttpContext.Session.GetInt32("CustomerId");
            if(custId != null)
            {
                shoppingCart.Userid = custId;
                shoppingCart.Productid = proid;
                _context.Add(shoppingCart);

            }
            
            await _context.SaveChangesAsync();
            //shoppingCart.Productid = proiud;
             return View(getall);
            
        }
        public async Task<IActionResult> ShoppingCart()
        {
            //ViewBag.Idcustomer = HttpContext.Session.GetInt32("CustomerId");
            var custId = HttpContext.Session.GetInt32("CustomerId");
            var modelContext = _context.ShoppingCarts.Where(x=> x.User.Userid==custId).Include(s => s.Product).Include(s => s.User);
            return View(await modelContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> ShoppingCart(decimal catrId)
        {
            var shoppingCart = await _context.ShoppingCarts.FindAsync(catrId);
            //shoppingCart.Userid = custId;
            _context.ShoppingCarts.Remove(shoppingCart);
            await _context.SaveChangesAsync();

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> CheckOut()
        {

            var custId = HttpContext.Session.GetInt32("CustomerId");
            var modelContext = _context.ShoppingCarts.Where(x => x.User.Userid == custId).Include(s => s.Product).Include(s => s.User);
            
            
            //await _context.SaveChangesAsync();
            return View(await modelContext.ToListAsync());
        }
        
        public async Task<IActionResult> CheckOuta()
        {
            var custId = HttpContext.Session.GetInt32("CustomerId");
            var modelContext = _context.ShoppingCarts.Where(x => x.User.Userid == custId).Include(s => s.Product).Include(s => s.User).ToList();
            var eamilcust = _context.UserloginFps.Where(x => x.User.Userid == custId).FirstOrDefault();
            


            try
            {
                if (custId != null)
                {

                    using SmtpClient mySmtpClient = new SmtpClient("smtp.office365.com", 587);
                    mySmtpClient.EnableSsl = true;

                    // set smtp-client with basicAuthentication
                    mySmtpClient.UseDefaultCredentials = false;
                    NetworkCredential basicAuthenticationInfo = new
                      NetworkCredential("mutasemshboul@outlook.com", "mutasem12345");
                    mySmtpClient.Credentials = basicAuthenticationInfo;

                    // add from,to mailaddresses
                    //use your email
                    MailAddress from = new MailAddress("mutasemshboul@outlook.com", "Market Store Admin");

                    //Send mail to:
                    //use customer email
                    MailboxAddress emailto = new MailboxAddress("user", eamilcust.Email);
                    MailAddress to = new MailAddress(eamilcust.Email, "Customer:");
                    using MailMessage myMail = new MailMessage(from, to);



                    // set subject and encoding
                    myMail.Subject = "Thank you for shopping";
                    myMail.SubjectEncoding = Encoding.UTF8;

                    // set body-message and encoding
                    myMail.Body = "<h1>Hello</h1><h3>Purchase completed successfully</h3>";
                    myMail.BodyEncoding = Encoding.UTF8;
                    // text or html
                    myMail.IsBodyHtml = true;

                    await mySmtpClient.SendMailAsync(myMail);
                    Console.WriteLine("Email Has Been Send");
                }

            }

            catch (SmtpException ex)
            {
                Console.WriteLine(ex.Message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }



            if (custId != null)
            {
                ProductuserFp productuserFp = new ProductuserFp();
                productuserFp.Userid = custId;
                int lastId = (int)_context.ProductuserFps.OrderByDescending(p => p.Productuserid).FirstOrDefault().Productuserid;
                foreach (var id in modelContext)
                {
                    productuserFp.Productuserid = ++lastId;

                    productuserFp.Productid = id.Productid;
                    productuserFp.Quantity = id.Quantity;
                    
                    _context.ProductuserFps.Add(productuserFp);
                    await _context.SaveChangesAsync();
                }

                var s = _context.ShoppingCarts.Where(x => x.Userid == custId).ToList();
                foreach (var item in s)
                {
                    var shoppingCart = await _context.ShoppingCarts.FindAsync(item.Id);
                    //shoppingCart.Userid = custId;
                    _context.ShoppingCarts.Remove(shoppingCart);
                    await _context.SaveChangesAsync();

                }
            }

            return RedirectToAction("Index");

        }
        //[HttpPost]
        //public async Task<IActionResult> DeleteCarts(decimal catrId)
        //{
        //    var shoppingCart = await _context.ShoppingCarts.FindAsync(catrId);
        //    //shoppingCart.Userid = custId;
        //    _context.ShoppingCarts.Remove(shoppingCart);
        //    await _context.SaveChangesAsync();

        //    return View();
        //}
        
        public async Task<JsonResult> AddCart( int proid)
        {
            ShoppingCart shoppingCart =new ShoppingCart();  
            var custId = HttpContext.Session.GetInt32("CustomerId");
            if (custId != null)
            {
                shoppingCart.Userid = custId;
                shoppingCart.Productid = proid;
                _context.Add(shoppingCart);
                await _context.SaveChangesAsync();
                return Json(1);

            }

            return Json(0);
        }

        public async Task<IActionResult> ContactUs() 
        {
            //var contactus = _context.ContactusFps.ToListAsync(); 
            //var contactusDynmic = _context.Contactdynmics.ToListAsync();
            //var getall = Tuple.Create<OnlineStoreFP.Models.ContactusFp,OnlineStoreFP.Models.Contactdynmic>(contactus, contactusDynmic);
            //return View(getall);
            return View(await _context.Contactdynmics.ToListAsync());

        }
        public async Task<IActionResult> Shops()
        {
            var modelContext = _context.ProductFps.Include(p => p.Store.Category);
            return View(await modelContext.ToListAsync());
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<JsonResult> UpdataQty(int id, int qty)
        {

            var cart = _context.ShoppingCarts.Find((decimal)id);

            cart.Quantity= qty;
            _context.ShoppingCarts.Update(cart);

            await _context.SaveChangesAsync();
           
            return Json(cart);
        }
    }
}

OnlineStoreFP/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStoreFP.Models;

namespace OnlineStoreFP.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly ModelContext _context;

        public ShoppingCartsController(ModelContext context)
        {
            _context = context;
        }

        // GET: ShoppingCarts
        public async Task<IActionResult> Index()
        {
            var modelContext = _context.ShoppingCarts.Include(s => s.Product).Include(s => s.User);
            return View(await modelContext.ToListAsync());
        }

        // GET: ShoppingCarts/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Create
        public IActionResult Create()
        {
            ViewData["Productid"] = new SelectList(_context.ProductFps, "Productid", "Productname");
            ViewData["Userid"] = new SelectList(_context.UserFps, "Userid", "Fname");
            return View();
        }

        // POST: ShoppingCarts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Userid,Productid,Quantity")] ShoppingCart shoppingCart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoppingCart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Productid"] = new SelectList(_context.ProductFps, "Productid", "Productid", shoppingCart.Productid);
            ViewData["Userid"] = new SelectList(_context.UserFps, "Userid", "Userid", shoppingCart.Userid);
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
            if (shoppingCart == null)
            {
                return NotFound();
            }
            ViewData["Productid"] = new SelectList(_context.ProductFps, "Productid", "Productid", shoppingCart.Productid);
            ViewData["Userid"] = new SelectList(_context.UserFps, "Userid", "Userid", shoppingCart.Userid);
            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Id,Userid,Productid,Quantity")] ShoppingCart shoppingCart)
        {
            if (id != shoppingCart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoppingCart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoppingCartExists(shoppingCart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Productid"] = new SelectList(_context.ProductFps, "Productid", "Productid", shoppingCart.Productid);
            ViewData["Userid"] = new SelectList(_context.UserFps, "Userid", "Userid", shoppingCart.Userid);
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
            _context.ShoppingCarts.Remove(shoppingCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("ShoppingCart", "Home"); 
        }

        private bool ShoppingCartExists(decimal id)
        {
            return _context.ShoppingCarts.Any(e => e.Id == id);
        }
    }
}

OnlineStoreFP/Views/Home/ShoppingCart.cshtml
@model IEnumerable<OnlineStoreFP.Models.ShoppingCart>
@{
    ViewData["Title"] = "ShoppingCart";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/homepage/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/homepage/css/style.css" type="text/css">
</head>

<body onload="Calc()">

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <a href="./shop.html">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var item in Model){
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img style="border-radius:20%;" width="100" height="100" src="~/Image/@item.Product.Imagepath">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>@Html.DisplayFor(modelItem => item.Product.Productname) </h6>
                                            <h5 id="prc" class="prc">@Html.DisplayFor(modelItem => item.Product.Price)</h5>
                                           
                                        </div>
                                    </td>
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input  class="qty" type="number" min = "1" value="1" onchange="Calc()" >
                                            </div>
                                        </div>
                                    </td>
                                    <td class="cart__price">  </td>
                                    <td><form asp-controller="ShoppingCarts" asp-action="Delete">
                                <input type="hidden" class="cartsid" name = "id"  asp-for="@item.Id" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> 
                                
                                </form></td>
                                    @*<td class="cart__close">< href="#" class="fa fa-close"></></td>*@
                                </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a asp-controller = "Home" asp-action="Shops">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="#" onclick="AddQty()" ><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            
                            <li>Total <span id="totalofsum"></span></li>
                        </ul>
                        <a asp-controller="Home" asp-action="CheckOut"   class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

   

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->

    <script>
        
        
        function Calc(){
            var sumAllProduct = 0
            const quantites = document.getElementsByClassName('qty');
            const prices = document.getElementsByClassName('prc');
            const eachPrice = document.getElementsByClassName('cart__price');

            for(var i=0; i<quantites.length; i++ ) {
              
                sumAllProduct += Number(prices[i].innerText) * Number(quantites[i].value);
                eachPrice[i].innerText = Number(prices[i].innerText) * Number(quantites[i].value) + " $";
                
            }
        
            document.getElementById('totalofsum').innerText = sumAllProduct + " $";
            document.getElementsByClassName('cart__price') = eachPrice;
        
        }
        

       function AddQty()
       {
          const quantites = document.getElementsByClassName('qty');
          const cartsid = document.getElementsByClassName('cartsid');
          
          for(var i = 0; i< quantites.length;i++)
          {
              var id = cartsid[i].value;
              var qty = quantites[i].value;


             $.ajax({
                url: "/Home/UpdataQty",
                type: "POST",
                data: { id:id, qty:qty},
                success: function (data) {

                    console.log(data);
                   }

                });


             
          }

           

       }
    </script>

    
   @* <script>

    var price = document.getElementsByClassName('TT')
    var sum11 = 0
    var quantity = document.getElementsByClassName('TTT')
    var sum = document.getElementsByClassName('TTTT')
    var totalofsum = document.getElementById('totalofsum')
    for (let i = 0; i < price.length; i++) {



        var sum1 = parseFloat(price[i].innerHTML) * parseFloat(quantity[i].innerHTML);
        sum11 += sum1
        sum[i].innerHTML = sum1;

    }
    totalofsum.innerHTML = 'Total of sum : ' +  sum11;

</script>*@
    <script src="~/homepage/js/jquery-3.3.1.min.js"></script>
    <script src="~/homepage/js/bootstrap.min.js"></script>
    <script src="~/homepage/js/jquery.nice-select.min.js"></script>
    <script src="~/homepage/js/jquery.nicescroll.min.js"></script>
    <script src="~/homepage/js/jquery.magnific-popup.min.js"></script>
    <script src="~/homepage/js/jquery.countdown.min.js"></script>
    <script src="~/homepage/js/jquery.slicknav.js"></script>
    <script src="~/homepage/js/mixitup.min.js"></script>
    <script src="~/homepage/js/owl.carousel.min.js"></script>
    <script src="~/homepage/js/main.js"></script>
</body>

</html>