OnlineStoreFP/Controllers/UasedashbordController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineStoreFP.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStoreFP.Controllers
{
    public class UasedashbordController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;


        public UasedashbordController(ModelContext context, IWebHostEnvironment _webHostEnviroment)
        {
            _context = context;
            this._webHostEnviroment = _webHostEnviroment;
        }

        public IActionResult Index()
        {
            var custid = HttpContext.Session.GetInt32("CustomerId");
            ViewBag.namecustomer = HttpContext.Session.GetString("CustomerName");
            if (custid != null)
            {
                var item2 = _context.ProductuserFps.Where(x => x.Userid == custid).FirstOrDefault();
                if(item2 == null)
                {
                    return View();
                }

                var item3 = _context.ProductFps.Where(x => x.Productid == item2.Productid).FirstOrDefault();
                var item4 = _context.UserFps.Where(x=> x.Userid == custid).FirstOrDefault();
                if (item3 != null)
                {
                ViewBag.Userinfo = item2;
                ViewBag.Userinfo2 = item3;
                ViewBag.Userinfo3 = item4;


                    var customerproduct = _context.ProductuserFps.Where(x => /*(x.Datefrom >= Dfrom && x.Dateto <= Dto) &&*/ x.Userid == custid).ToList();
                var customer = _context.UserFps.Where(x => x.Userid == custid).ToList();
                var product = _context.ProductFps.ToList();
                var multi = from c in customer
                            join pc in customerproduct on c.Userid equals pc.Userid
                            join pp in product on pc.Productid equals pp.Productid

                            select new JoinTable { productFp = pp, userFp = c, productuserFp = pc };

                if (customerproduct != null)
                {
                    return View(multi);
                }
                else
                {
                    return View();
                }
                }
                
               
            }
            return View();
        }
        [HttpPost]
        public IActionResult Index(DateTime Dto ,DateTime Dfrom)
        {
            var custid = HttpContext.Session.GetInt32("CustomerId");
            ViewBag.namecustomer = HttpContext.Session.GetString("CustomerName");
            if (custid != null)
            {
                var item2 = _context.ProductuserFps.Where(x => x.Userid == custid).FirstOrDefault();

                var item3 = _context.ProductFps.Where(x => x.Productid == item2.Productid).FirstOrDefault();
                ViewBag.Userinfo = item2;
                ViewBag.Userinfo2 = item3;

                var customerproduct = _context.ProductuserFps.Where(x => /*(x.Datefrom >= Dfrom && x.Dateto <= Dto) &&*/ x.Userid == custid).ToList();
                var customer = _context.UserFps.Where(x => x.Userid == custid).ToList();
                var product = _context.ProductFps.ToList();
                var multi = from c in customer
                            join pc in customerproduct on c.Userid equals pc.Userid
                            join pp in product on pc.Productid equals pp.Productid

                            select new JoinTable { productFp = pp, userFp = c, productuserFp = pc };

                if (customerproduct != null)
                {
                    return View(multi);
                }
                else
                {
                    return View();
                }
            }
            return View();  
            


           
        }
        public IActionResult UserProfil()
        {
            
            var custid = HttpContext.Session.GetInt32("CustomerId");
            if (custid != null)
            {
                var item2 = _context.UserFps.Where(x => x.Userid == custid).FirstOrDefault();
                ViewBag.emailcustomer = HttpContext.Session.GetString("CustomerEmail");
                ViewBag.passwordcustomer = HttpContext.Session.GetString("CustomerPassword");
                ViewBag.Userinfo = item2;
                ViewBag.Userinfo3 = item2;

                UpdateProfile updateProfile = new UpdateProfile();

                return View(updateProfile);
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserProfil( UpdateProfile updateProfile)
        {
            var custid = HttpContext.Session.GetInt32("CustomerId");
            if (custid != null)
            {
                var item2 = _context.UserFps.Where(x => x.Userid == custid).FirstOrDefault();
                ViewBag.emailcustomer = HttpContext.Session.GetString("CustomerEmail");
                ViewBag.passwordcustomer = HttpContext.Session.GetString("CustomerPassword");
                ViewBag.Userinfo = item2;
                ViewBag.Userinfo3 = item2;

                var x = _context.UserFps.Where(x => x.Userid == custid).FirstOrDefault();
                var y = _context.UserloginFps.Where(x => x.Userid == custid).FirstOrDefault();
                if (updateProfile.FName != null)
                {
                    x.Fname = updateProfile.FName;

                }
                if (updateProfile.LName != null)
                {
                    x.Lname = updateProfile.LName;
                }
                if (updateProfile.ImageFile != null)
                {
                    string wwwRootPath = _webHostEnviroment.WebRootPath;
                    string fileName = Guid.NewGuid().ToString() + "_" + updateProfile.ImageFile.FileName;
                    string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await updateProfile.ImageFile.CopyToAsync(fileStream);
                    }
                    x.Imagepath = fileName;
                    _context.UserFps.Update(x);
                    await _context.SaveChangesAsync();

                }

                _context.Update(x);
                await _context.SaveChangesAsync();
                if (updateProfile.Email != null)
                {
                    y.Email = updateProfile.Email;
                }
                _context.Update(y);
                await _context.SaveChangesAsync();
                if (updateProfile.Password != null)
                {
                    y.Password = updateProfile.Password;
                }
                _context.Update(y);
                await _context.SaveChangesAsync();



                return View(updateProfile);
            }
            else
            {
                return View();
            }
        }


    }
}

OnlineStoreFP/Views/Uasedashbord/Index.cshtml
@model IEnumerable<JoinTable>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UasedashbordLayout.cshtml";
}

<h1>Welecome @ViewBag.namecustomer </h1>

@*<form asp-controller="Uasedashbord"asp-action="Index">
    
    <label>Date from</label>
    <input type="date" id="Dfrom" name="Dfrom" />
    <label>Date To</label>
    <input type="date" id="Dto" name="Dto" />
    <button type="submit" class="btn btn-success">Submit</button>
</form>*@


@if (Model != null)
{
    <table class="table table-light" >
        <tr>
            <th>Name</th>
            <th>productname</th>
            @*<th>Date from</th>
                <th>Date To</th>*@
            <th>productprice</th>
            <th>quantity</th>
            <th>SUM</th>


        </tr>
        @foreach (var item in Model)
        {
            <tr >
                <td>@item.userFp.Fname</td>
                <td>@item.productFp.Productname</td>
                @*<td>@item.productuserFp.Datefrom</td>
                    <td>@item.productuserFp.Dateto</td>*@
                <td class="TT">@item.productFp.Price</td>
                <td class="TTT">@item.productuserFp.Quantity</td>
                <td class="TTTT"></td>


            </tr>
        }
        ​
    </table>
    }


@*<h4 class="text text-black" id="totalofsum"></h4>*@


<script>

    var price = document.getElementsByClassName('TT')
    var sum11 = 0
    var quantity = document.getElementsByClassName('TTT')
    var sum = document.getElementsByClassName('TTTT')
    var totalofsum = document.getElementById('totalofsum')
    for (let i = 0; i < price.length; i++) {



        var sum1 = parseFloat(price[i].innerHTML) * parseFloat(quantity[i].innerHTML);
        sum11 += sum1
        sum[i].innerHTML = sum1;

    }
    totalofsum.innerHTML = 'Total of sum : ' +  sum11;

</script>

OnlineStoreFP/Views/Uasedashbord/UserProfil.cshtml
@model OnlineStoreFP.Models.UpdateProfile
@{
    ViewData["Title"] = "UserProfil";
    Layout = "~/Views/Shared/_UasedashbordLayout.cshtml";
}

<h1>UserProfile</h1>
@if (Model != null)
{
    <div class="row">
        <!-- Column -->
                    <div class="col-lg-4 col-xlg-3 col-md-5">
            <div class="card">
                <div class="card-body">
                    <center class="mt-4"> 
                        <img src="~/Image/@ViewBag.Userinfo.Imagepath" class="img-circle"width="150" />
                        <h4 class="card-title mt-2">@ViewBag.Userinfo.Fname</h4>
                        
                        <div class="row text-center justify-content-md-center">
                            
                           
                        </div>
                    </center>
                </div>
            </div>
        </div>
        <!-- Column -->
        <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-7">
            <div class="card">
                <!-- Tab panes -->
                            <div class="card-body">
                    <form class="form-horizontal form-material mx-2" asp-controller="Uasedashbord" asp-action="UserProfil" enctype="multipart/form-data" >
                        <div class="form-group">
                            <label class="col-md-12">First Name</label>
                            <div class="col-md-12">
                                <input type="text" asp-for="FName" placeholder="@ViewBag.Userinfo.Fname " 
                                                class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Last Name</label>
                            <div class="col-md-12">
                                <input type="text" asp-for="LName" placeholder="@ViewBag.Userinfo.Lname" 
                                                class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="example-email" class="col-md-12">Email</label>
                            <div class="col-md-12">
                                <input type="email" asp-for="Email" placeholder=@ViewBag.emailcustomer
                                                class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Choose Image</label>
                            <div class="col-md-12">
                                <input asp-for="ImageFile" class="form-control form-control-line">
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Password</label>
                            <div class="col-md-12">
                                <input type="text" asp-for="Password" placeholder="@ViewBag.passwordcustomer"
                                                class="form-control form-control-line">
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button class="btn btn-success" >Update Profile</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Column -->
                </div>
}